// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://djaxvumqpzjfctklcoaf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqYXh2dW1xcHpqZmN0a2xjb2FmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MDI2ODAsImV4cCI6MjA3MTk3ODY4MH0.cJ7w-82mnAgqgW7Oq5hqfIGwOO5BVvEHkQgDtr5SLZo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});